mail:                    # mails are sent using swift mailer
  enabled: 0             # 1/0 smtp mailing enabled?
  username: user         # smtp username
  password: pass         # smtp password
  from: user@example.com # from email address
  to: user@example.com   # to email address (recipient)
  subjectPrefix: Warehouse Deal Found # prefix mail subjects with this
  smtp: smtp.gmail.com   # smtp hostname
  port: 25               # smtp port
  security: ssl          # security, blank for unsecure, ssl/tls for secure connections, check swiftmailer documentation for more details
log:
  enabled: 1             # 1/0 logging enabled?
  file: log/system       # log file name
hooks:                   # hooks - leave blank to disable
  shellStart:            # shell command that is executed on starting the script
  shellDeal:             # shell command that is executed if a deal was found | '%TITLE%', '%CONDITION%', '%PRICE%' is replaced by the findings
  shellNoDeal:           # shell command that is executed if there is no deal
options:
  engine: Amazon                    # Name of the Engine to use, e.g. Amazon results in \dstuecken\WdAlerts\Crawler\Amazon\Engine
  updateInterval: 30                # interval in seconds for new requests to amazon
  enableMacOsNotificationHandler: 1 # show growl like notifications in mac os x
  enableMacOsSpeechOutput: 1        # shell_exec say command to enable speech output on mac os
  enableConsoleTextOutput: 1        # write status to console
  userAgent: Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.102011-10-16 20:23:10  # user agent that is used for retrieving the pages
  acceptLanguage: de                # Accept-Language header for requests
  proxy:                            # https proxy, e.g. tcp://85.26.146.169:80